package northwind;
// Generated 6 mai 2021 à 09:51:14 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SalesReports generated by hbm2java
 */
@Entity
@Table(name = "sales_reports", schema = "NORTHWIND", catalog = "NORTHWIND")
public class SalesReports implements java.io.Serializable {

	private String groupBy;
	private String display;
	private String title;
	private String filterRowSource;
	private int default_;

	public SalesReports() {
	}

	public SalesReports(String groupBy, int default_) {
		this.groupBy = groupBy;
		this.default_ = default_;
	}

	public SalesReports(String groupBy, String display, String title, String filterRowSource, int default_) {
		this.groupBy = groupBy;
		this.display = display;
		this.title = title;
		this.filterRowSource = filterRowSource;
		this.default_ = default_;
	}

	@Id

	@Column(name = "group_by", unique = true, nullable = false, length = 50)
	public String getGroupBy() {
		return this.groupBy;
	}

	public void setGroupBy(String groupBy) {
		this.groupBy = groupBy;
	}

	@Column(name = "display", length = 50)
	public String getDisplay() {
		return this.display;
	}

	public void setDisplay(String display) {
		this.display = display;
	}

	@Column(name = "title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "filter_row_source", length = 199)
	public String getFilterRowSource() {
		return this.filterRowSource;
	}

	public void setFilterRowSource(String filterRowSource) {
		this.filterRowSource = filterRowSource;
	}

	@Column(name = "default", nullable = false)
	public int getDefault_() {
		return this.default_;
	}

	public void setDefault_(int default_) {
		this.default_ = default_;
	}

}
