package northwind;
// Generated 6 mai 2021 à 09:51:14 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products", schema = "NORTHWIND", catalog = "NORTHWIND")
public class Products implements java.io.Serializable {

	private Integer id;
	private String supplierIds;
	private String productCode;
	private String productName;
	private String description;
	private BigDecimal standardCost;
	private BigDecimal listPrice;
	private Integer reorderLevel;
	private Integer targetLevel;
	private String quantityPerUnit;
	private int discontinued;
	private Integer minimumReorderQuantity;
	private String category;
	private Blob attachments;
	private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);
	private Set<PurchaseOrderDetails> purchaseOrderDetailses = new HashSet<PurchaseOrderDetails>(0);
	private Set<InventoryTransactions> inventoryTransactionses = new HashSet<InventoryTransactions>(0);

	public Products() {
	}

	public Products(BigDecimal listPrice, int discontinued) {
		this.listPrice = listPrice;
		this.discontinued = discontinued;
	}

	public Products(String supplierIds, String productCode, String productName, String description,
			BigDecimal standardCost, BigDecimal listPrice, Integer reorderLevel, Integer targetLevel,
			String quantityPerUnit, int discontinued, Integer minimumReorderQuantity, String category, Blob attachments,
			Set<OrderDetails> orderDetailses, Set<PurchaseOrderDetails> purchaseOrderDetailses,
			Set<InventoryTransactions> inventoryTransactionses) {
		this.supplierIds = supplierIds;
		this.productCode = productCode;
		this.productName = productName;
		this.description = description;
		this.standardCost = standardCost;
		this.listPrice = listPrice;
		this.reorderLevel = reorderLevel;
		this.targetLevel = targetLevel;
		this.quantityPerUnit = quantityPerUnit;
		this.discontinued = discontinued;
		this.minimumReorderQuantity = minimumReorderQuantity;
		this.category = category;
		this.attachments = attachments;
		this.orderDetailses = orderDetailses;
		this.purchaseOrderDetailses = purchaseOrderDetailses;
		this.inventoryTransactionses = inventoryTransactionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "supplier_ids", length = 199)
	public String getSupplierIds() {
		return this.supplierIds;
	}

	public void setSupplierIds(String supplierIds) {
		this.supplierIds = supplierIds;
	}

	@Column(name = "product_code", length = 25)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "product_name", length = 50)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "description", length = 199)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "standard_cost", scale = 4)
	public BigDecimal getStandardCost() {
		return this.standardCost;
	}

	public void setStandardCost(BigDecimal standardCost) {
		this.standardCost = standardCost;
	}

	@Column(name = "list_price", nullable = false, scale = 4)
	public BigDecimal getListPrice() {
		return this.listPrice;
	}

	public void setListPrice(BigDecimal listPrice) {
		this.listPrice = listPrice;
	}

	@Column(name = "reorder_level")
	public Integer getReorderLevel() {
		return this.reorderLevel;
	}

	public void setReorderLevel(Integer reorderLevel) {
		this.reorderLevel = reorderLevel;
	}

	@Column(name = "target_level")
	public Integer getTargetLevel() {
		return this.targetLevel;
	}

	public void setTargetLevel(Integer targetLevel) {
		this.targetLevel = targetLevel;
	}

	@Column(name = "quantity_per_unit", length = 50)
	public String getQuantityPerUnit() {
		return this.quantityPerUnit;
	}

	public void setQuantityPerUnit(String quantityPerUnit) {
		this.quantityPerUnit = quantityPerUnit;
	}

	@Column(name = "discontinued", nullable = false)
	public int getDiscontinued() {
		return this.discontinued;
	}

	public void setDiscontinued(int discontinued) {
		this.discontinued = discontinued;
	}

	@Column(name = "minimum_reorder_quantity")
	public Integer getMinimumReorderQuantity() {
		return this.minimumReorderQuantity;
	}

	public void setMinimumReorderQuantity(Integer minimumReorderQuantity) {
		this.minimumReorderQuantity = minimumReorderQuantity;
	}

	@Column(name = "category", length = 50)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "attachments")
	public Blob getAttachments() {
		return this.attachments;
	}

	public void setAttachments(Blob attachments) {
		this.attachments = attachments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<OrderDetails> getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<PurchaseOrderDetails> getPurchaseOrderDetailses() {
		return this.purchaseOrderDetailses;
	}

	public void setPurchaseOrderDetailses(Set<PurchaseOrderDetails> purchaseOrderDetailses) {
		this.purchaseOrderDetailses = purchaseOrderDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<InventoryTransactions> getInventoryTransactionses() {
		return this.inventoryTransactionses;
	}

	public void setInventoryTransactionses(Set<InventoryTransactions> inventoryTransactionses) {
		this.inventoryTransactionses = inventoryTransactionses;
	}

}
